//
// WSNewsSource.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WSNewsSource: Codable {

    /** The identifier of the news source. You can use this with our other endpoints. */
    public var _id: String?
    /** The name of the news source */
    public var name: String?
    /** A description of the news source */
    public var _description: String?
    /** The URL of the homepage. */
    public var url: String?
    public var category: WSNewsCategory?
    public var language: WSNewsLanguage?
    public var country: WSNewsCountry?

    public init(_id: String? = nil, name: String? = nil, _description: String? = nil, url: String? = nil, category: WSNewsCategory? = nil, language: WSNewsLanguage? = nil, country: WSNewsCountry? = nil) {
        self._id = _id
        self.name = name
        self._description = _description
        self.url = url
        self.category = category
        self.language = language
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case url
        case category
        case language
        case country
    }

}
