//
// WSNewsSortBy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The order to sort the articles in. Possible options: relevancy, popularity, publishedAt. */
public enum WSNewsSortBy: String, Codable {
    case relevancy = "relevancy"
    case popularity = "popularity"
    case publishedat = "publishedAt"
}