//
// WSNewsLanguage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum WSNewsLanguage: String, Codable {
    case ar = "ar"
    case de = "de"
    case en = "en"
    case es = "es"
    case fr = "fr"
    case he = "he"
    case it = "it"
    case nl = "nl"
    case no = "no"
    case pt = "pt"
    case ru = "ru"
    case se = "se"
    case ud = "ud"
    case zh = "zh"
}