//
// WSNewsSortBy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum WSNewsSortBy: String, Codable {
    case relevancy = "relevancy"
    case popularity = "popularity"
    case publishedat = "publishedAt"
}