//
// WSNewsErrorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WSNewsErrorResponse: Codable {

    public var status: String?
    public var code: String?
    public var message: String?

    public init(status: String? = nil, code: String? = nil, message: String? = nil) {
        self.status = status
        self.code = code
        self.message = message
    }


}
