//
// WSNewsSourcesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WSNewsSourcesResponse: Codable {

    public var status: String?
    public var sources: [WSNewsSource]?

    public init(status: String? = nil, sources: [WSNewsSource]? = nil) {
        self.status = status
        self.sources = sources
    }


}
